package:
  name: gdx-reader
  version: "0.1.1"
 
source:
  git_url: ../
  git_tag: master

requirements:
  build:
    - python
    - cython
    - numpy ==1.10.1
  run:
    - python
    - numpy
    - pandas
 
about:
  summary: "Read GDX files fast using the GAMS C API"