package:
  name: gdx-reader
  version: "0.2.6"
 
source:
  git_url: ../
  git_tag: master

requirements:
  build:
    - python
    - cython
    - numpy
  run:
    - python
    - numpy
    - pandas
 
build:
  script:
    - python setup.py install

about:
  summary: "Read GDX files fast using the GAMS C API"
  license: GPLv3
  license_file: LICENSE
  home: https://github.com/joelgoop/gdx-reader